name: Create New Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  xcpretty_check:
    name: XCPretty Code Check
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Install xcpretty
        run: |
          gem install xcpretty

      - name: Run xcpretty Project Analysis
        run: |
          echo "Running XCPretty code analysis..."
          xcodebuild -project 'backdoor.xcodeproj' -list | xcpretty
          
      - name: Run xcpretty Code Check
        run: |
          echo "Running XCPretty Swift code check..."
          xcodebuild clean -project 'backdoor.xcodeproj' -scheme 'backdoor (Debug)' | xcpretty --color
          xcodebuild analyze -project 'backdoor.xcodeproj' -scheme 'backdoor (Debug)' -destination 'generic/platform=iOS' CODE_SIGNING_ALLOWED=NO | xcpretty --color --report html
          
      - name: Upload XCPretty Report
        uses: actions/upload-artifact@v4
        with:
          name: xcpretty-report
          path: build/reports/

  build:
    name: Build and Package
    needs: xcpretty_check
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Install dependencies (packages)
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid
          brew install 7zip gnu-sed
          gem install xcpretty

      - name: Compile
        run: | 
          mkdir upload
          # Use optimization level -Onone to enable previews and avoid Swift compilation blocking issues
          make package SCHEME="'backdoor (Release)'" CFLAGS="-Onone" SWIFT_OPTIMIZATION_LEVEL="-Onone" SWIFT_COMPILATION_MODE="singlefile"
          mv packages/* upload/

      - name: Get Version Number
        id: get_version
        run: |
          VERSION=$( /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Payload/backdoor.app/Info.plist )
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Setup
        run: |
          mv upload/backdoor.ipa upload/backdoor_v${VERSION}.ipa
          cp upload/backdoor_v${VERSION}.ipa upload/backdoor_v${VERSION}.tipa

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: backdoor v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            upload/*ipa
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}


